### ISSUE TITLE
 Logo Proposal for daddit

### ISSUE THREAD

**Issue by leonardoderoy** [skywalker212/daddit#1]
Hellow @skywalker212 
I'm a graphic designer and I like to support your project because I believe a good logo that reflects your project at its best can help the project publicity and trustability, also i'm an open source enthusiast. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Leonardo Deroy

Graphic Designer

**Comment by skywalker212** [comment]
@leonardoderoy  That's great!
Go on, make that fantastic logo.

**Comment by leonardoderoy** [comment]
hellow @skywalker212  before starting I would like to know exactly what your project is about and the exact name would also be very helpful

**Comment by skywalker212** [comment]
@leonardoderoy Our project is similar to Reddit but with a lot of additional functionality. It is specially made for people from my college, DAIICT. Hence the name **daddit**. Daddit is actually an abbreviation of DA-iict+reDDIT.
The main aim is to make people able to share stuff easily. It is community-centric.

**Comment by skywalker212** [comment]
@leonardoderoy any updates?
